setwd("C:/Users/988003/Downloads")
climate = read.csv("climate_change.csv")
test = subset(climate,climate$Year<=2006)
model = lm(Temp ~ MEI+CO2+CH4+N2O+CFC.11+CFC.12+TSI+Aerosols , data=test)
summary(model)
cor(test)
model1 = lm(Temp ~ MEI+N2O+TSI+Aerosols , data=test)
summary(model1)
model2= step(model)
summary(model2)
pred=predict(model2)
summary(pred)
