flu = read.csv("FluTest.csv")
fluT = read.csv("FluTrain.csv")
lILI=log(fluT$ILI)
m1=lm(lILI~fluT$Queries, data = fluT)
summary(model)
head(flu)
pred1= exp(predict(model,newdata=flu))
which(flu$Week == "2012-03-11 - 2012-03-17")
sort(pred1)
pred1[11]
install.packages("zoo")
library(zoo)
ILILag3 = lag(zoo(flu$ILI), -3, na.pad=TRUE)
str(ILILag3)
flu$ILILag2 = coredata(ILILag2)
str(flu$ILI)
summary(flu)
